const stringField = (name: string) => ({
  name,
  type: 'string',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const numberField = (name: string) => ({
  name,
  type: 'number',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const dateField = (name: string) => ({
  name,
  type: 'date',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const objectField = (name: string) => ({
  name,
  type: 'object',
  searchable: false,
  aggregatable: false,
  readFromDocValues: false,
});

export const IndexPatternRuntimeJavaVulnerabilitiesKnownFields = [
  stringField('_id'),
  stringField('_index'),
  numberField('_score'),
  objectField('_source'),
  stringField('matcher.request_id'),
  stringField('matcher.source'),
  stringField('matcher.url'),
  dateField('matcher.generated_at'),
  stringField('runtime_java.component._inventory_id'),
  stringField('runtime_java.component._inventory_index'),
  numberField('runtime_java.component._document_version'),
  stringField('runtime_java.component.artifact_id'),
  stringField('runtime_java.component.checksum.hash.sha1'),
  stringField('runtime_java.component.confidence'),
  stringField('runtime_java.component.evidence_source'),
  stringField('runtime_java.component.file.hash.sha1'),
  stringField('runtime_java.component.file.path'),
  stringField('runtime_java.component.group_id'),
  stringField('runtime_java.component.package.name'),
  stringField('runtime_java.component.package.type'),
  stringField('runtime_java.component.package.version'),
  stringField('runtime_java.component.package_type'),
  stringField('runtime_java.component.process.command_line'),
  stringField('runtime_java.component.process.name'),
  numberField('runtime_java.component.process.pid'),
  numberField('runtime_java.component.process.start'),
  stringField('runtime_java.component.purl'),
  stringField('runtime_java.component.runtime_path'),
  stringField('runtime_java.component.sha1'),
  dateField('runtime_java.component.state.modified_at'),
  numberField('runtime_java.component.state.document_version'),
  stringField('runtime_java.component.version'),
  stringField('runtime_java.confidence'),
  stringField('runtime_java.evidence_source'),
  stringField('runtime_java.inventory_id'),
  stringField('runtime_java.operation'),
  stringField('runtime_java.vulnerability.affected_range'),
  stringField('runtime_java.vulnerability.description'),
  stringField('runtime_java.vulnerability.fixed_versions'),
  stringField('runtime_java.vulnerability.id'),
  stringField('runtime_java.vulnerability.match_confidence'),
  dateField('runtime_java.vulnerability.matched_at'),
  stringField('runtime_java.vulnerability.operation'),
  stringField('runtime_java.vulnerability.references'),
  stringField('runtime_java.vulnerability.severity'),
  stringField('runtime_java.vulnerability.source'),
  stringField('runtime_java.vulnerability.title'),
  stringField('schema_version'),
  stringField('wazuh.agent.groups'),
  stringField('wazuh.agent.host.architecture'),
  stringField('wazuh.agent.host.hostname'),
  stringField('wazuh.agent.host.os.name'),
  stringField('wazuh.agent.host.os.platform'),
  stringField('wazuh.agent.host.os.type'),
  stringField('wazuh.agent.host.os.version'),
  stringField('wazuh.agent.id'),
  stringField('wazuh.agent.name'),
  stringField('wazuh.agent.version'),
  stringField('wazuh.cluster.name'),
  stringField('wazuh.cluster.node'),
  stringField('wazuh.session.id'),
  stringField('wazuh.session.module'),
  stringField('wazuh.session.scan_mode'),
];
