const stringField = (name: string) => ({
  name,
  type: 'string',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const keywordField = (name: string) => ({
  name,
  type: 'string',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const numberField = (name: string) => ({
  name,
  type: 'number',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const dateField = (name: string) => ({
  name,
  type: 'date',
  searchable: true,
  aggregatable: true,
  readFromDocValues: true,
});

const objectField = (name: string) => ({
  name,
  type: 'object',
  searchable: false,
  aggregatable: false,
  readFromDocValues: false,
});

export const IndexPatternRuntimeJavaVulnerabilitiesKnownFields = [
  stringField('_id'),
  stringField('_index'),
  numberField('_score'),
  objectField('_source'),
  stringField('matcher.request_id'),
  keywordField('matcher.request_id.keyword'),
  stringField('matcher.source'),
  keywordField('matcher.source.keyword'),
  stringField('matcher.url'),
  keywordField('matcher.url.keyword'),
  dateField('matcher.generated_at'),
  stringField('runtime_java.component._inventory_id'),
  keywordField('runtime_java.component._inventory_id.keyword'),
  stringField('runtime_java.component._inventory_index'),
  keywordField('runtime_java.component._inventory_index.keyword'),
  numberField('runtime_java.component._document_version'),
  stringField('runtime_java.component.artifact_id'),
  keywordField('runtime_java.component.artifact_id.keyword'),
  stringField('runtime_java.component.checksum.hash.sha1'),
  keywordField('runtime_java.component.checksum.hash.sha1.keyword'),
  stringField('runtime_java.component.confidence'),
  keywordField('runtime_java.component.confidence.keyword'),
  stringField('runtime_java.component.evidence_source'),
  keywordField('runtime_java.component.evidence_source.keyword'),
  stringField('runtime_java.component.file.hash.sha1'),
  keywordField('runtime_java.component.file.hash.sha1.keyword'),
  stringField('runtime_java.component.file.path'),
  keywordField('runtime_java.component.file.path.keyword'),
  stringField('runtime_java.component.group_id'),
  keywordField('runtime_java.component.group_id.keyword'),
  stringField('runtime_java.component.package.name'),
  keywordField('runtime_java.component.package.name.keyword'),
  stringField('runtime_java.component.package.type'),
  keywordField('runtime_java.component.package.type.keyword'),
  stringField('runtime_java.component.package.version'),
  keywordField('runtime_java.component.package.version.keyword'),
  stringField('runtime_java.component.package_type'),
  keywordField('runtime_java.component.package_type.keyword'),
  stringField('runtime_java.component.process.command_line'),
  keywordField('runtime_java.component.process.command_line.keyword'),
  stringField('runtime_java.component.process.name'),
  keywordField('runtime_java.component.process.name.keyword'),
  numberField('runtime_java.component.process.pid'),
  numberField('runtime_java.component.process.start'),
  stringField('runtime_java.component.purl'),
  keywordField('runtime_java.component.purl.keyword'),
  stringField('runtime_java.component.runtime_path'),
  keywordField('runtime_java.component.runtime_path.keyword'),
  stringField('runtime_java.component.sha1'),
  keywordField('runtime_java.component.sha1.keyword'),
  dateField('runtime_java.component.state.modified_at'),
  numberField('runtime_java.component.state.document_version'),
  stringField('runtime_java.component.version'),
  keywordField('runtime_java.component.version.keyword'),
  stringField('runtime_java.confidence'),
  keywordField('runtime_java.confidence.keyword'),
  stringField('runtime_java.evidence_source'),
  keywordField('runtime_java.evidence_source.keyword'),
  stringField('runtime_java.inventory_id'),
  keywordField('runtime_java.inventory_id.keyword'),
  stringField('runtime_java.operation'),
  keywordField('runtime_java.operation.keyword'),
  stringField('runtime_java.vulnerability.affected_range'),
  keywordField('runtime_java.vulnerability.affected_range.keyword'),
  stringField('runtime_java.vulnerability.description'),
  keywordField('runtime_java.vulnerability.description.keyword'),
  stringField('runtime_java.vulnerability.fixed_versions'),
  keywordField('runtime_java.vulnerability.fixed_versions.keyword'),
  stringField('runtime_java.vulnerability.id'),
  keywordField('runtime_java.vulnerability.id.keyword'),
  stringField('runtime_java.vulnerability.match_confidence'),
  keywordField('runtime_java.vulnerability.match_confidence.keyword'),
  dateField('runtime_java.vulnerability.matched_at'),
  stringField('runtime_java.vulnerability.operation'),
  keywordField('runtime_java.vulnerability.operation.keyword'),
  stringField('runtime_java.vulnerability.references'),
  keywordField('runtime_java.vulnerability.references.keyword'),
  stringField('runtime_java.vulnerability.severity'),
  keywordField('runtime_java.vulnerability.severity.keyword'),
  stringField('runtime_java.vulnerability.source'),
  keywordField('runtime_java.vulnerability.source.keyword'),
  stringField('runtime_java.vulnerability.title'),
  keywordField('runtime_java.vulnerability.title.keyword'),
  stringField('schema_version'),
  keywordField('schema_version.keyword'),
  stringField('wazuh.agent.groups'),
  keywordField('wazuh.agent.groups.keyword'),
  stringField('wazuh.agent.host.architecture'),
  keywordField('wazuh.agent.host.architecture.keyword'),
  stringField('wazuh.agent.host.hostname'),
  keywordField('wazuh.agent.host.hostname.keyword'),
  stringField('wazuh.agent.host.os.name'),
  keywordField('wazuh.agent.host.os.name.keyword'),
  stringField('wazuh.agent.host.os.platform'),
  keywordField('wazuh.agent.host.os.platform.keyword'),
  stringField('wazuh.agent.host.os.type'),
  keywordField('wazuh.agent.host.os.type.keyword'),
  stringField('wazuh.agent.host.os.version'),
  keywordField('wazuh.agent.host.os.version.keyword'),
  stringField('wazuh.agent.id'),
  keywordField('wazuh.agent.id.keyword'),
  stringField('wazuh.agent.name'),
  keywordField('wazuh.agent.name.keyword'),
  stringField('wazuh.agent.version'),
  keywordField('wazuh.agent.version.keyword'),
  stringField('wazuh.cluster.name'),
  keywordField('wazuh.cluster.name.keyword'),
  stringField('wazuh.cluster.node'),
  keywordField('wazuh.cluster.node.keyword'),
  stringField('wazuh.session.id'),
  keywordField('wazuh.session.id.keyword'),
  stringField('wazuh.session.module'),
  keywordField('wazuh.session.module.keyword'),
  stringField('wazuh.session.scan_mode'),
  keywordField('wazuh.session.scan_mode.keyword'),
];
